version: '3.8'
services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"

  solidity-contracts:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./contracts:/usr/src/app/contracts  # Update this line if necessary

